# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Лабораторная работа №3| Клиент")
        MainWindow.resize(580, 566)
        MainWindow.setStyleSheet("background: #454545;\n"
"padding: .5em 5px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 118, 561, 441))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setStyleSheet(" display: block;\n"
"    color: rgb(197, 197, 197);\n"
"    text-align: center;\n"
"    padding: 14px 16px;\n"
"    text-decoration: none;\n"
"background: #454545;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(8, 5, 511, 361))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit#lineEdit{\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 600;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QLineEdit#lineEdit:hover { background: rgba(255,255,255,.2); }\n"
"QLineEdit#lineEdit:pressed { background: white; }")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit#plainTextEdit{\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 600;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPlainTextEdit#plainTextEdit:hover { background: rgba(255,255,255,.2); }\n"
"QPlainTextEdit#plainTextEdit:pressed { background: white; }")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPushButton#pushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#pushButton:pressed { background: rgb(64,199,129); }")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2 {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPushButton#pushButton_2:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#pushButton_2:pressed { background: white; }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4 {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton#pushButton_4:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#pushButton_4:pressed { background: rgb(152,15,0); }\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(5, 6, 511, 361))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit#lineEdit_4{\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 600;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QLineEdit#lineEdit_4:hover { background: rgba(255,255,255,.2); }\n"
"QLineEdit#lineEdit_4:pressed { background: white; }")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit#lineEdit_5{\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 600;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QLineEdit#lineEdit_5:hover { background: rgba(255,255,255,.2); }\n"
"QLineEdit#lineEdit_5:pressed { background: white; }")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5 {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 700;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPushButton#pushButton_5:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton#pushButton_5:pressed { background: white; }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit#plainTextEdit_2{\n"
"  display: inline-block;\n"
"  color: white;\n"
"  font-weight: 600;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border: 2px solid;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"\n"
"QPlainTextEdit#plainTextEdit_2:hover { background: rgba(255,255,255,.2); }\n"
"QPlainTextEdit#plainTextEdit_2:pressed { background: white; }")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        self.NameLabel.setGeometry(QtCore.QRect(10, 20, 571, 94))
        self.NameLabel.setStyleSheet("body{list-style-type: none;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    overflow: hidden;\n"
"    background-color: #333;\n"
"}\n"
"QLabel#NameLabel{\n"
"    display: block;\n"
"    color: white;\n"
"    text-align: center;\n"
"    padding: 14px 16px;\n"
"    text-decoration: none;\n"
"}")
        self.NameLabel.setObjectName("NameLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Текст сообщения.."))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
        self.pushButton_2.setText(_translate("MainWindow", "Подключится"))
        self.pushButton_4.setText(_translate("MainWindow", "Очистить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Чат"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Адрес сервера.."))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Порт сервера.."))
        self.pushButton_5.setText(_translate("MainWindow", "Сгенерировать данные для подключения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Настройки"))
        self.NameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Лабораторная работа №3</span></p><p align=\"center\"><span style=\" font-style:italic;\">Выполнили: Скребнев Л., Чернуцкая Е., Кутузов Л.</span></p></body></html>"))
