.TH "lab_1_2.MainForm.Bigramms" 3 "Sun Dec 6 2020" "Version 1" "Лабораторная работа №1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lab_1_2.MainForm.Bigramms
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBigramms\fP (string a, string b, bool count=true)"
.br
.ti -1c
.RI "void \fBSetB\fP (string \fBB\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBA\fP => a"
.br
.ti -1c
.RI "string \fBB\fP => b"
.br
.ti -1c
.RI "bool \fBFull\fP => Count"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file method_3\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lab_1_2\&.MainForm\&.Bigramms\&.Bigramms (string a, string b, bool count = \fCtrue\fP)"

.PP
Definition at line 18 of file method_3\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void lab_1_2\&.MainForm\&.Bigramms\&.SetB (string B)"

.PP
Definition at line 25 of file method_3\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string lab_1_2\&.MainForm\&.Bigramms\&.A => a"

.PP
Definition at line 28 of file method_3\&.cs\&.
.SS "string lab_1_2\&.MainForm\&.Bigramms\&.B => b"

.PP
Definition at line 29 of file method_3\&.cs\&.
.SS "bool lab_1_2\&.MainForm\&.Bigramms\&.Full => Count"

.PP
Definition at line 30 of file method_3\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Лабораторная работа №1 from the source code\&.
