.TH "lab_1_2.MainForm" 3 "Sun Dec 6 2020" "Version 1" "Лабораторная работа №1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lab_1_2.MainForm
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBigramms\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainForm\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Освободить все используемые ресурсы\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file Form1\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "lab_1_2\&.MainForm\&.MainForm ()"

.PP
Definition at line 15 of file Form1\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void lab_1_2\&.MainForm\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Освободить все используемые ресурсы\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP истинно, если управляемый ресурс должен быть удален; иначе ложно\&.
.RE
.PP

.PP
Definition at line 16 of file Form1\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Лабораторная работа №1 from the source code\&.
