# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 573)
        MainWindow.setStyleSheet("background: #454545;\n"
                                 "padding: .5em 5px;\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(0, 0, 566, 577))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.NameLabel = QtWidgets.QLabel(self.splitter_2)
        self.NameLabel.setStyleSheet("body{list-style-type: none;\n"
                                     "    margin: 0;\n"
                                     "    padding: 0;\n"
                                     "    overflow: hidden;\n"
                                     "    background-color: #333;\n"
                                     "}\n"
                                     "QLabel#NameLabel{\n"
                                     "    color: white;\n"
                                     "    text-align: center;\n"
                                     "    padding: 14px 16px;\n"
                                     "    text-decoration: none;\n"
                                     "}")
        self.NameLabel.setObjectName("NameLabel")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("    color: rgb(197, 197, 197);\n"
                                     "    text-align: center;\n"
                                     "    padding: 14px 16px;\n"
                                     "    text-decoration: none;\n"
                                     "background: #454545;")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("    color: white;\n"
                               "    text-align: center;\n"
                               "    padding: 14px 16px;\n"
                               "    text-decoration: none;\n"
                               "background: #454545;")
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WindowChat = QtWidgets.QPlainTextEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.WindowChat.setFont(font)
        self.WindowChat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.WindowChat.setStyleSheet("QPlainTextEdit#WindowChat{\n"
                                      "  color: white;\n"
                                      "  font-weight: 600;\n"
                                      "  text-decoration: none;\n"
                                      "  padding: .5em 2em;\n"
                                      "  outline: none;\n"
                                      "  border: 2px solid;\n"
                                      "  border-radius: 1px;\n"
                                      "} \n"
                                      "\n"
                                      "QPlainTextEdit#WindowChat:hover { background: rgba(255,255,255,.2); }\n"
                                      "QPlainTextEdit#WindowChat:pressed { background: white; }")
        self.WindowChat.setObjectName("WindowChat")
        self.verticalLayout.addWidget(self.WindowChat)
        self.send_Text = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.send_Text.setFont(font)
        self.send_Text.setMouseTracking(False)
        self.send_Text.setStyleSheet("QLineEdit#send_Text{\n"
                                     "  color: white;\n"
                                     "  font-weight: 600;\n"
                                     "  text-decoration: none;\n"
                                     "  padding: .5em 2em;\n"
                                     "  outline: none;\n"
                                     "  border: 2px solid;\n"
                                     "  border-radius: 1px;\n"
                                     "} \n"
                                     "\n"
                                     "QLineEdit#send_Text:hover { background: rgba(255,255,255,.2); }\n"
                                     "QLineEdit#send_Text:pressed { background: white; }")
        self.send_Text.setObjectName("send_Text")
        self.verticalLayout.addWidget(self.send_Text)
        self.btn_connect = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.btn_connect.setFont(font)
        self.btn_connect.setStyleSheet("QPushButton#btn_connect {\n"
                                       "  color: white;\n"
                                       "  font-weight: 700;\n"
                                       "  text-decoration: none;\n"
                                       "  padding: .5em 2em;\n"
                                       "  outline: none;\n"
                                       "  border: 2px solid;\n"
                                       "  border-radius: 1px;\n"
                                       "} \n"
                                       "\n"
                                       "QPushButton#btn_connect:hover { background: rgba(255,255,255,.2); }\n"
                                       "QPushButton#btn_connect:pressed { background: white; }")
        self.btn_connect.setObjectName("btn_connect")
        self.verticalLayout.addWidget(self.btn_connect)
        self.btn_send = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.btn_send.setFont(font)
        self.btn_send.setStyleSheet("QPushButton#btn_send {\n"
                                    "  color: white;\n"
                                    "  font-weight: 700;\n"
                                    "  text-decoration: none;\n"
                                    "  padding: .5em 2em;\n"
                                    "  outline: none;\n"
                                    "  border: 2px solid;\n"
                                    "  border-radius: 1px;\n"
                                    "} \n"
                                    "\n"
                                    "QPushButton#btn_send:hover { background: rgba(255,255,255,.2); }\n"
                                    "QPushButton#btn_send:pressed { background: rgb(64,199,129); }")
        self.btn_send.setObjectName("btn_send")
        self.verticalLayout.addWidget(self.btn_send)
        self.btn_clear = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(87)
        font.setStrikeOut(False)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("QPushButton#btn_clear {\n"
                                     "  color: white;\n"
                                     "  font-weight: 700;\n"
                                     "  text-decoration: none;\n"
                                     "  padding: .5em 2em;\n"
                                     "  outline: none;\n"
                                     "  border: 2px solid;\n"
                                     "  border-radius: 1px;\n"
                                     "} \n"
                                     "QPushButton#btn_clear:hover { background: rgba(255,255,255,.2); }\n"
                                     "QPushButton#btn_clear:pressed { background: rgb(152,15,0); }\n"
                                     "")
        self.btn_clear.setObjectName("btn_clear")
        self.verticalLayout.addWidget(self.btn_clear)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("    color: gray;\n"
                                 "    text-align: center;\n"
                                 "    padding: 14px 16px;\n"
                                 "    text-decoration: none;\n"
                                 "background: #454545;")
        self.tab_2.setObjectName("tab_2")
        self.splitter = QtWidgets.QSplitter(self.tab_2)
        self.splitter.setGeometry(QtCore.QRect(-10, 0, 521, 391))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.ip_address = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ip_address.setFont(font)
        self.ip_address.setStyleSheet("QLineEdit#ip_address{\n"
                                      "  color: white;\n"
                                      "  font-weight: 600;\n"
                                      "  text-decoration: none;\n"
                                      "  padding: .5em 2em;\n"
                                      "  outline: none;\n"
                                      "  border: 2px solid;\n"
                                      "  border-radius: 1px;\n"
                                      "} \n"
                                      "\n"
                                      "QLineEdit#ip_address:hover { background: rgba(255,255,255,.2); }\n"
                                      "QLineEdit#ip_address:pressed { background: white; }")
        self.ip_address.setText("")
        self.ip_address.setObjectName("ip_address")
        self.port_address = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.port_address.setFont(font)
        self.port_address.setStyleSheet("QLineEdit#port_address{\n"
                                        "  color: white;\n"
                                        "  font-weight: 600;\n"
                                        "  text-decoration: none;\n"
                                        "  padding: .5em 2em;\n"
                                        "  outline: none;\n"
                                        "  border: 2px solid;\n"
                                        "  border-radius: 1px;\n"
                                        "} \n"
                                        "\n"
                                        "QLineEdit#port_address:hover { background: rgba(255,255,255,.2); }\n"
                                        "QLineEdit#port_address:pressed { background: white; }")
        self.port_address.setText("")
        self.port_address.setObjectName("port_address")
        self.p_number = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.p_number.setFont(font)
        self.p_number.setStyleSheet("QLineEdit#p_number{\n"
                                    "  color: white;\n"
                                    "  font-weight: 600;\n"
                                    "  text-decoration: none;\n"
                                    "  padding: .5em 2em;\n"
                                    "  outline: none;\n"
                                    "  border: 2px solid;\n"
                                    "  border-radius: 1px;\n"
                                    "} \n"
                                    "\n"
                                    "QLineEdit#p_number:hover { background: rgba(255,255,255,.2); }\n"
                                    "QLineEdit#p_number:pressed { background: white; }")
        self.p_number.setText("")
        self.p_number.setObjectName("p_number")
        self.e_number = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.e_number.setFont(font)
        self.e_number.setStyleSheet("QLineEdit#e_number{\n"
                                    "  color: white;\n"
                                    "  font-weight: 600;\n"
                                    "  text-decoration: none;\n"
                                    "  padding: .5em 2em;\n"
                                    "  outline: none;\n"
                                    "  border: 2px solid;\n"
                                    "  border-radius: 1px;\n"
                                    "} \n"
                                    "\n"
                                    "QLineEdit#e_number:hover { background: rgba(255,255,255,.2); }\n"
                                    "QLineEdit#e_number:pressed { background: white; }")
        self.e_number.setText("")
        self.e_number.setObjectName("e_number")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.ip_address)
        MainWindow.setTabOrder(self.ip_address, self.port_address)
        MainWindow.setTabOrder(self.port_address, self.p_number)
        MainWindow.setTabOrder(self.p_number, self.btn_connect)
        MainWindow.setTabOrder(self.btn_connect, self.send_Text)
        MainWindow.setTabOrder(self.send_Text, self.btn_send)
        MainWindow.setTabOrder(self.btn_send, self.btn_clear)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №2"))
        self.NameLabel.setText(_translate("MainWindow",
                                          "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Лабораторная работа №2</span></p><p align=\"center\"><span style=\" font-style:italic;\">Выполнили: Скребнев Л., Чернуцкая Е., Кутузов Л.</span></p></body></html>"))
        self.send_Text.setPlaceholderText(_translate("MainWindow", "Текст сообщения.."))
        self.btn_connect.setText(_translate("MainWindow", "Подключится"))
        self.btn_send.setText(_translate("MainWindow", "Отправить"))
        self.btn_clear.setText(_translate("MainWindow", "Очистить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Чат"))
        self.ip_address.setPlaceholderText(_translate("MainWindow", "Адрес сервера.."))
        self.port_address.setPlaceholderText(_translate("MainWindow", "Порт сервера.."))
        self.p_number.setPlaceholderText(_translate("MainWindow", "P ="))
        self.e_number.setPlaceholderText(_translate("MainWindow", "e ="))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Настройки"))
